import type { Metadata, Viewport } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";
import MainLayout from "@/core/components/species/MainLayout";

const oswald = Oswald({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Delícias da Tia Sandra",
    template: "%s | Delícias da Tia Sandra",
  },
  description: "Generated by create next app",
  formatDetection: {
    address: false,
    date: false,
    email: false,
    telephone: false,
    url: false,
  }
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: '#ffffff', // '#f8bb21'
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <MainLayout>
          {children}
        </MainLayout>
      </body>
    </html>
  );
}
