import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Delícias Tia Sandra",
    template: "%s | Delícias Tia Sandra",
  },
  description: "Generated by create next app",
  formatDetection: {
    address: false,
    date: false,
    email: false,
    telephone: false,
    url: false,
  }
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: '#ffffff', // '#f8bb21'
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`${inter.className} has-[#backdrop]:overflow-hidden overflow-auto`}>{children}</body>
    </html>
  );
}
